/*
 * Do whatever you want with it.
 */
package ecc.view;

import ecc.EllipticCurve;
import static ecc.EllipticCurve.DEF_GX;
import static ecc.EllipticCurve.DEF_GY;
import ecc.Point;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Olayinka
 */
public class Home extends javax.swing.JFrame {

    public static EllipticCurve ECC_CURVE;
    public static Point BASE;

    /**
     * Creates new form Home
     *
     * @throws java.lang.Exception
     */
    public Home() throws Exception {
        initComponents();
        ECC_CURVE = new EllipticCurve();
        BASE = new Point(DEF_GX, DEF_GY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elliptic Curve Cryptography");
        setBounds(new java.awt.Rectangle(50, 50, 0, 0));
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Home home = null;
                try {
                    home = new Home();
                } catch (Exception ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
                assert home != null;
                CardLayout cardLayout = (CardLayout) home.getContentPane().getLayout();
                Menu menu = new Menu();
                DiffieHellmanView view = new DiffieHellmanView();
                EccDsaView dsaView = new EccDsaView();
                home.add(menu);
                home.add(view);
                home.add(dsaView);
                menu.mInitCOmponents();
                view.mInitComponents();
                dsaView.mInitComponents();
                cardLayout.addLayoutComponent(view, "DIFFIE_HELLMAN");
                cardLayout.addLayoutComponent(menu, "MENU");
                cardLayout.addLayoutComponent(dsaView, "ECC_DSA");
                home.setVisible(true);
                cardLayout.show(home.getContentPane(), "MENU");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
